############################
## CHANGE THESE
############################

baseURL: "https://patrickpulfer.github.io/pulfer.cloud"
title: pulfer.cloud

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
